apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-gbd8
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-gbd8
    app.kubernetes.io/part-of: ci1t-43256-0096-app
  name: devfile-sample-gbd8
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-gbd8
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-gbd8
    spec:
      containers:
      - image: quay.io/stonesoup_perfscale/ci1t-43256-0096-tenant/ci1t-43256-0096-app/devfile-sample-gbd8@sha256:8b0158c2036ab212495b38e257bae06e953c207cb5191b7f363fff2c1327cecf
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
